version: '3.8'

services:
  db:
    image: postgres:14
    container_name: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabasepass
      POSTGRES_DB: metabase
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  metabase:
    image: metabase/metabase:v0.55.1
    container_name: metabase_app
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabasepass
      MB_DB_HOST: db
    depends_on:
      - db
    restart: always

volumes:
  db_data:
